apiVersion: v1
kind: Secret
metadata:
  name: {{ include "organizat-backend.fullname" . }}-secret
  labels:
    {{- include "organizat-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  SUPABASE_URL: {{ .Values.env.supabaseUrl | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.env.supabaseServiceRoleKey | quote }}
  DATABASE_URL: {{ .Values.env.databaseUrl | quote }}
  ANON_KEY: {{ .Values.env.supabaseAnonKey | quote }}
  SERVICE_ROLE: {{ .Values.env.serviceRole | quote }}
